# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += seco-imx8qm-c26.dtb 

dtb-$(CONFIG_ARCH_FSL_IMX8MM) += seco-imx8mm-c61.dtb

dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += seco-imx8qxp-c57.dtb

dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += seco-imx8mq-c12.dtb\
				 seco-imx8mq-c20.dtb\

subdir-y := overlays


